Brumby_mvc/Models/otc.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Brumby_mvc.Models
{
    public class otc
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public double Open { get; set; }
        public double High { get; set; }
        public double Low { get; set; }
        public double Close { get; set; }
        /// <summary>
        /// 漲跌
        /// </summary>
        public string UpDown { get; set; }
        /// <summary>
        /// 成交股數
        /// </summary>
        public string DealVolume { get; set; }
        /// <summary>
        /// 成交筆數
        /// </summary>
        public string DealNums { get; set; }
        /// <summary>
        /// 成交金額
        /// </summary>
        public string DealPrice { get; set; }
        /// <summary>
        /// 最後揭示買價
        /// </summary>
        public string LastBuyPrice { get; set; }
        /// <summary>
        /// 最後揭示賣價
        /// </summary>
        public string LastSellPrice { get; set; }
        /// <summary>
        /// 發行股數
        /// </summary>
        public double NowCapital { get; set; }
        /// <summary>
        /// 次日漲停價
        /// </summary>
        public double MaxPriceT { get; set; }
        /// <summary>
        /// 次日跌停價
        /// </summary>
        public double MinPriceT { get; set; }
        public string TurnoverRate { get; set; }
    }
}

Brumby_mvc/Models/otcTurnoverate.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Brumby_mvc.Models
{
    public class otcTurnoverate
    {
        public int Id { get; set; }
        public string s_date { get; set; }
        public int s_rank { get; set; }
        public string s_id { get; set; }
        public string s_name { get; set; }
        public string s_deal { get; set; }
        public string s_market { get; set; }
        public double s_turnoverate { get; set; }
    }
}

Brumby_mvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Brumby_mvc.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Brumby_mvc/Controllers/StockController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Brumby_mvc.Controllers
{
    public class StockController : Controller
    {
        List<Models.otc> data = new List<Models.otc>();
        // GET: Stock
        public ActionResult Listed()
        {
            return View();
        }

        public ActionResult OTC()
        {
            cs.Stock.OTC otc = new cs.Stock.OTC();
            data = otc.ParseOTCInfo("111/09/20");
            ViewBag.OTC = data;
            return View();
        }
        public ActionResult GetOTCturnoverate()
        {
            Console.WriteLine("Bag");
            return RedirectToAction("OTC");
        }
    }
}

Brumby_mvc/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Brumby_mvc/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Brumby_mvc/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Brumby_mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Gentelella Alela! | </title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>
<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a href="~/Views/Home/Index.cshtml" class="site_title"><i class="fa fa-paw"></i> <span>Eric</span></a>
                    </div>

                    <div class="clearfix"></div>

                    <!-- menu profile quick info -->
                    <div class="profile clearfix">
                        <div class="profile_pic">
                            <img src="~/images/header.jpg" class="img-circle profile_img">
                        </div>
                        <div class="profile_info">
                            <span>Welcome,</span>
                            <h2>Brumby -tw</h2>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <!-- /menu profile quick info -->

                    <br />

                    <!-- sidebar menu -->
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        <div class="menu_section">
                            <h3>General</h3>
                            <ul class="nav side-menu">
                                <li>
                                    <a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li>@Html.ActionLink("Index", "Index", "Home")</li>
                                        <li>@Html.ActionLink("About", "About", "Home")</li>
                                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-stop-circle"></i> Stock <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li>@Html.ActionLink("OTC", "OTC", "Stock")</li>
                                        <li>@Html.ActionLink("Listed", "About", "Home")</li>
                                        <li>@Html.ActionLink("Pre", "Contact", "Home")</li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="menu_section">
                            <h3>Live On</h3>
                            <ul class="nav side-menu">
                                <li><a href="javascript:void(0)"><i class="fa fa-laptop"></i> Landing Page @*<span class="label label-success pull-right">Coming Soon</span>*@</a></li>
                            </ul>
                        </div>

                    </div>
                    <!-- /sidebar menu -->
                    <!-- /menu footer buttons -->
                    <div class="sidebar-footer hidden-small">
                        <a data-toggle="tooltip" data-placement="top" title="Settings">
                            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                        </a>
                        <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                            <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                        </a>
                        <a data-toggle="tooltip" data-placement="top" title="Lock">
                            <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                        </a>
                        <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                        </a>
                    </div>
                    <!-- /menu footer buttons -->
                </div>
            </div>

            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <nav>
                        <div class="nav toggle">
                            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                        </div>

                        <ul class="nav navbar-nav navbar-right">
                            <li class="">
                                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    <img src="~/images/header.jpg" alt="">Brumby
                                    <span class="fa fa-angle-down"></span>
                                </a>
                                <ul class="dropdown-menu dropdown-usermenu pull-right">
                                    <li><a href="javascript:;"> Profile</a></li>
                                    <li>
                                        <a href="javascript:;">
                                            <span class="badge bg-red pull-right">50%</span>
                                            <span>Settings</span>
                                        </a>
                                    </li>
                                    <li><a href="javascript:;">Help</a></li>
                                    <li><a href="login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                                </ul>
                            </li>

                            <li role="presentation" class="dropdown">
                                <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                                    <i class="fa fa-envelope-o"></i>
                                    <span class="badge bg-green">6</span>
                                </a>
                                <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                                    <li>
                                        <a>
                                            <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                            <span>
                                                <span>John Smith</span>
                                                <span class="time">3 mins ago</span>
                                            </span>
                                            <span class="message">
                                                Film festivals used to be do-or-die moments for movie makers. They were where...
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a>
                                            <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                            <span>
                                                <span>Type of service</span>
                                                <span class="time">3 mins ago</span>
                                            </span>
                                            <span class="message">
                                                Film festivals used to be do-or-die moments for movie makers. They were where...
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a>
                                            <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                            <span>
                                                <span>John Smith</span>
                                                <span class="time">3 mins ago</span>
                                            </span>
                                            <span class="message">
                                                Film festivals used to be do-or-die moments for movie makers. They were where...
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a>
                                            <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                            <span>
                                                <span>John Smith</span>
                                                <span class="time">3 mins ago</span>
                                            </span>
                                            <span class="message">
                                                Film festivals used to be do-or-die moments for movie makers. They were where...
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <div class="text-center">
                                            <a>
                                                <strong>See All Alerts</strong>
                                                <i class="fa fa-angle-right"></i>
                                            </a>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
            <!-- /top navigation -->
            <!-- page content -->
            <div class="right_col" role="main">
                <div class="">
                    @RenderBody()
                </div>
            </div>
            <!-- /page content -->
            <!-- footer content -->
            <footer>
                <div class="pull-right">
                    Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
                </div>
                <div class="clearfix"></div>
            </footer>
            <!-- /footer content -->
        </div>
    </div>

    @Scripts.Render("~/Scripts/js")
</body>
</html>

Brumby_mvc/Views/Stock/OTC.cshtml
@using Brumby_mvc.Models;
@{
    //Layout = null;
    List<otc> data = ViewBag.OTC;
}

@*<button>@Html.ActionLink("GetOTCturnoverate", "GetOTCturnoverate")</button>*@
<div class="content-wrap">
    <div class="main">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-8 p-r-0 title-margin-right">
                    <div class="page-header">
                        <div class="page-title">
                            <h1>Hello <span>Welcome</span></h1>
                        </div>
                    </div>
                </div>
                <!-- /# column -->
                <div class="col-lg-4 p-l-0 title-margin-left">
                    <div class="page-header">
                        <div class="page-title">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
                                <li class="breadcrumb-item active">Table-Basic</li>
                            </ol>
                        </div>
                    </div>
                </div>
                <!-- /# column -->
            </div>
            <!-- /# row -->
            <section id="main-content">
                <div class="row">
                    <!-- /# column -->
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-title">
                                <h4>OTC</h4>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped">
                                        <thead>
                                            <tr>
                                                <th>Date</th>
                                                <th>Id</th>
                                                <th>Type</th>
                                                <th>Name</th>
                                                <th>Open</th>
                                                <th>High</th>
                                                <th>Low</th>
                                                <th>Close</th>
                                                <th>UpDown</th>
                                                <th>DealVolume</th>
                                                <th>DealNums</th>
                                                <th>DealPrice</th>
                                                <th>LastBuyPrice</th>
                                                <th>LastSellPrice</th>
                                                <th>NowCapital</th>
                                                <th>MaxPriceT</th>
                                                <th>MinPriceT</th>
                                                <th>TurnoverRate</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @{
                                                if (data != null)
                                                {
                                                    foreach (otc item in data)
                                                    {
                                                        <tr>
                                                            <th scope="row">@item.Date</th>
                                                            <td>@item.Id</td>
                                                            <td>@item.Type</td>
                                                            <td>@item.Name</td>
                                                            <td>@item.Open</td>
                                                            <td>@item.High</td>
                                                            <td>@item.Low</td>
                                                            <td>@item.Close</td>
                                                            <td>@item.UpDown</td>
                                                            <td>@item.DealVolume</td>
                                                            <td>@item.DealNums</td>
                                                            <td>@item.DealPrice</td>
                                                            <td>@item.LastBuyPrice</td>
                                                            <td>@item.LastSellPrice</td>
                                                            <td>@item.NowCapital</td>
                                                            <td>@item.MaxPriceT</td>
                                                            <td>@item.MinPriceT</td>
                                                            <td>@item.TurnoverRate</td>
                                                        </tr>
                                                    }
                                                }
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /# row -->
            </section>
        </div>
    </div>
</div>